-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 17:50:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feira
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feira
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feira` DEFAULT CHARACTER SET utf8 ;
USE `feira` ;

-- -----------------------------------------------------
-- Table `feira`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feira`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `feira`.`tbl_usuario` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feira`.`tbl_feirante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feira`.`tbl_feirante` ;

CREATE TABLE IF NOT EXISTS `feira`.`tbl_feirante` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` TEXT NOT NULL,
  `forma_de_pagamento` VARCHAR(100) NOT NULL,
  `faz_entrega` VARCHAR(3) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feira`.`tbl_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feira`.`tbl_admin` ;

CREATE TABLE IF NOT EXISTS `feira`.`tbl_admin` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
